apiVersion: metal3.io.sigs.k8s.io/v1alpha1
kind: HardwareClassification
metadata:
  name: hardwareclassification-sample
  namespace: metal3
  labels:
      hardwareclassification-sample: matches
spec:
  expectedValidationConfiguration:
      CPU:
         minimumCount: 4
         minimumSpeed: "2.7"
      Disk:
         minimumCount: 1
         maximumCount: 1
         minimumIndividualSizeGB: 200
         maximumIndividualSizeGB: 3000
      RAM:
         minimumSizeGB: 6
         maximumSizeGB: 180
      NIC:
         minimumCount: 1
         maximumCount: 7
