apiVersion: metal3.io/v1alpha1
kind: HardwareClassification
metadata:
  name: hardwareclassification-sample1
  namespace: metal3
  labels:
    hardwareclassification-sample: matches
    hardwareclassification-error: All
spec:
  hardwareCharacteristics:
      cpu:
         architecture : "x86_64"
         minimumCount: 48
         maximumCount: 72
         minimumSpeedMHz: 1000
         maximumSpeedMHz: 3600
      disk:
         minimumCount: 1
         maximumCount: 8
         minimumIndividualSizeGB: 10
         maximumIndividualSizeGB: 3000
      ram:
         minimumSizeGB: 1
         maximumSizeGB: 180
      nic:
         minimumCount: 1
         maximumCount: 7
      systemVendor:
         manufacturer: "QEMU"
         productName: "Standard PC"
      firmware:
         bios:
            vendor: "SeaBIOS"
            minorVersion: "1.5.6"
            majorVersion: "2.5.6"
