apiVersion: metal3.io.sigs.k8s.io/v1alpha1
kind: HardwareClassificationController
metadata:
  name: hardwareclassificationcontroller-sample
spec:
  namespace: metal3
  expectedValidationConfiguration:
        - profileName: Profile 1
          minimumCPU:
                count: 2
          minimumDisk:
                sizeBytesGB: 35
                numberOfDisks: 2
          minimumNICS:
                numberOfNICS: 2
          minimumRAM: 8
          systemVendor:
                name: Dell Inc.
          firmware:
                version:
                    RAID: "RAID1"
        - profileName: Profile 2
          minimumCPU:
                count: 8
          minimumDisk:
                sizeBytesGB: 50
                numberOfDisks: 4
          minimumNICS:
                numberOfNICS: 8
          minimumRAM: 16
