apiVersion: metal3.io.sigs.k8s.io/v1alpha1
kind: HardwareClassification
metadata:
  name: hardwareclassification-sample
  namespace: metal3
  labels:
    test: pass
spec:
  expectedValidationConfiguration:
      CPU:
         minimumCount: 48
         maximumCount: 72
         minimumSpeed: "2.7"
         maximumSpeed: "3.6"
      Disk:
         minimumCount: 1
         maximumCount: 7
         minimumIndividualSizeGB: 200
         maximumIndividualSizeGB: 3000
      RAM:
         minimumSizeGB: 6
         maximumSizeGB: 180
      NIC:
         minimumCount: 1
         maximumCount: 7
